### ISSUE TITLE
Update /preview 'Send test' to accept user provided inputs

### ISSUE THREAD

**Issue by ChcJohnie** [webscopeio/mailingui-web#111]

**Comment by iamhectorsosa** [comment]
I think this Radix Primitive would work great here:

Popover: https://www.radix-ui.com/docs/primitives/components/popover
Can grab inspo from this implementation: https://ui.shadcn.com/docs/components/popover

Just make sure to adapt to our colors and theme. Also make sure to avoid using any classes that are library specific if you go with adopting Shad's implementation.

Also we need some sort of feedback. Maybe the easiest would be an implementation on the button (with loading, success and failure states). Might also need to implement the popover as controlled.

Feel free to propose anything you see fit for this.

@ChcJohnie

**Comment by iamhectorsosa** [comment]
Also, for the time being we will keep using this testing API. This endpoint belongs to React Email (which parent company is Resend). For our use case, let's change the text with "Powered by [react.email](https://react.email/)".

I think this would make most sense. If you check the emails they also do great use of that brand.

![image](https://github.com/webscopeio/mailingui-web/assets/77650775/1f29fba2-7a4b-4c3d-945a-ff62504f7438)

**Comment by iamhectorsosa** [comment]
![image](https://github.com/webscopeio/mailingui-web/assets/77650775/6a79d3ae-2a34-49df-9b0f-e1d37151f42d)

**Comment by iamhectorsosa** [comment]
Closed by #112
