### ISSUE TITLE
Remove `Text` component dependency from `List` component

### ISSUE THREAD

**Issue by ericvalcik** [webscopeio/mailingui-web#139]
We want our components to be easy to copy and paste into the user's codebase and work with as few dependencies as possible. Right now the `List` component has a dependency on another component from our library `Text`.

It would be nice to remove that dependency, so we don't import anything from `@mailingui/components` in the `List` component, but keep the functionality and design the same as it is now. Afaik, `List` is the only component that is dependent on another component from our library so IMO it would be nice for all of our components to be independent of each other.

https://github.com/webscopeio/mailingui-web/blob/5e11969637a7194401a87f042bce644c7ad60802/src/mailingui/components/list/List.tsx#L11

**Comment by iamhectorsosa** [comment]
Here's to get a bit familiar with the library. @DanielPuchala target this after the other two issues assigned or if time allows.
