### ISSUE TITLE
Inconsistencies and minor issues on the home page

### ISSUE THREAD

**Issue by alexxander** [webscopeio/mailingui-web#155]
1. First of all, I don't really think the CTA text on the home page is clear. At first, I was not sure how to get to the docs. "Get started" or "See the Docs" would be more straightforward. "Explore components" is actually a good CTA in my opinion, but it opens the installation docs page, which is very weird.
2. A minor detail, there is a slight inconsistency between the CTA in the hero section and the CTA below the components "Explore components" vs "Explore Components".
3. It actually feels a bit weird to have the CTA under the actual links to the components. I'd actually expect the link to go to the very preview of the components it is under (or one that is quite similar to it) :sweat_smile:

**Comment by ericvalcik** [comment]
Resolved in #157
