### ISSUE TITLE
Improve the docs

### ISSUE THREAD

**Issue by alexxander** [webscopeio/mailingui-web#156]
1. I'd consider highlighting the fact that the components are intended to be used as copy-paste snippets (As this is not the usual approach and it might be confusing.)
2. I'd probably show an opinionated structure of the files that are necessary for the components to work (ideally somewhere close to the beginning of the docs). So that the users can have a better overview of what is necessary to set up as soon as possible.
3. I'd consider simplifying the way we talk about the theme file. I'd probably only suggest the way we like the most sticking to a specific opinion and trying to prevent confusion. I don't really like the formulation of "place the file somewhere in the project". If we want to communicate the fact that it is not completely necessary to keep the structure, I'd rather mention it in a side note.
4. Just a detail, but I don't quite like the fact that the theme alias reads "@mailingui/themes", while it exports just a single theme :sweat_smile:

**Comment by ericvalcik** [comment]
I can take this issue, assigning myself and will follow this up with a PR where we can discuss more.

**Comment by ericvalcik** [comment]
Resolved in #157
