### ISSUE TITLE
Please fix the readme to update pnpm version

### ISSUE THREAD

**Issue by iamhectorsosa** [webscopeio/mailingui-web#187]
```
~/documents/webscopeio/mailingui-web (main ✔) npm -v
9.6.7
~/documents/webscopeio/mailingui-web (main ✔) node -v
v20.3.0
~/documents/webscopeio/mailingui-web (main ✔) pnpm -v
8.6.9
```

**Comment by ericvalcik** [comment]
@iamhectorsosa I had to install a fresh version of node because I didn't have the `v20` version yet installed and I saw that the latest pnpm version is `8.6.11`. Shouldn't we rather use pnpm `8.6.11` instead of `8.6.9` ?

**Comment by iamhectorsosa** [comment]
I'm fine with either version of pnpm and node. Maybe I would be inclined in using a LTS version of node though.

**Comment by ericvalcik** [comment]
The current lts is the `v18`, `v20` is not an LTS yet
