### ISSUE TITLE
Update `/templates` page styles according to design

### ISSUE THREAD

**Issue by danad02** [webscopeio/mailingui-web#24]
Update `/templates` page styles according to design. Here's [the figma design](https://www.figma.com/file/c4UktJQ8gG3oU5QisMgE09/Email-components?node-id=607-1775&t=IyU7pTOIllrhGEys-0).

Use mobile-first approach.

**Comment by jvorcak** [comment]
Let's release the minimalistic template for now and try whether the overall concept works :)
