### ISSUE TITLE
Improving the Badges component primitive and adding Examples to the web

### ISSUE THREAD

**Issue by ericvalcik** [webscopeio/mailingui-web#89]
I think there are still some features that could be added to the `Badge` component primitive. I'm thinking about adding the following props:

- [x]  **dot** - just like in the [tailwind UI](https://tailwindui.com/components/application-ui/elements/badges#component-007ef3476f2ffe8bda7f37965d6ee434) docs, add an option to have a dot on the left side of the text inside the badge.
- [x] **rounded/pill** - this option would make the badges completely rounded - pill-shaped.
- [x] **noBorder** or **border** - this option would add or remove a border from the Badge.

For each new prop and all the existing ones, I will create an example as well.

Do you guys have any other ideas or thoughts about the props I proposed @iamhectorsosa @jvorcak ?

**Comment by iamhectorsosa** [comment]
Looking good! Remember to test these, I know some clients won't fully support the props mentioned (i.e., rounded corners).

**Comment by ericvalcik** [comment]
[This PR](https://github.com/webscopeio/mailingui-web/pull/90) should resolve this issue, however, there are still some issues with some clients:

- Outlook on Windows - badges are rendered but the styling is not consistent, check it out [here](https://testi.at/proj/xQLHvRTkmTVxJSQWnCOznio) for example.
- Office 365 Dark (macOS) - check the link above to view it.
- Dot Badges - [testi.at link](https://testi.at/proj/N9ASPXcZ3yt6R1hLbHe1Btp) to the test, Outlook + two other do not render it correctly (yahoo and gmail on IE 11)
